### ISSUE TITLE
How to determine sigma for heatmap?

### ISSUE THREAD

**Issue by Wang-Yu-Qing** [NikolasEnt/soccernet-calibration-sportlight#3]
I found the sigma is fixed as value 3 for image of size [270, 480] in train_config.yaml:
```
loss:
  num_refinement_stages: ${model.params.nn_module.num_refinement_stages}
  stride: 2
  sigma: 3.0
  pred_size: [270, 480]
```
If the image size is [h, w], how to determine a good sigma? I read from the solution post that it should be **2px**, what is this value exactly? Thanks!
